[package]
name = "wgpu_framework"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.31.1"
egui-wgpu = "0.31.1"
egui-winit = "0.31.1"
env_logger = "0.11.8"
glam = "0.30.3"
log = "0.4.27"
pollster = "0.4.0"
wgpu = "24.0.0"
winit = "0.30.11"